### ISSUE TITLE
Does not work with latest iOS SDK due to lack of armv7s arch

### ISSUE THREAD

**Issue by cyphers** [phamquy/iOSFFmpeg#1]

**Comment by phamquy** [comment]
Take a look at this to see how to generate armv7s static library from armv7 version, I didnt try myself.
(1) http://www.galloway.me.uk/2012/09/hacking-up-an-armv7s-library
(2) https://github.com/phamquy/ffmpeg-ios-compile

give it a try, and I would love to hear back from you.
